version: "3.8"
services:
  web:
    build: .
    runtime: nvidia
    environment:
      - TORCH_DEVICE=cuda
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ocr_db
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ocr_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
